version: '3.9'

services:
  postgres:
    container_name: "postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /data/postgres
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    # networks:
    #   - bespoked-bikes
    expose:
      - "5432"
    restart: unless-stopped

  pgadmin:
    container_name: "pgadmin"
    depends_on:
      - 'postgres'
    image: dpage/pgadmin4
    # env_file:
    #   - .docker-env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    # networks:
    #   - bespoked-bikes
    restart: unless-stopped

  # bike-trail-server:
  #   container_name: "bike-trail-server"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # image: public.ecr.aws/x0l0e7m3/bespoked-bike-trail:latest
  #   # image: bespoked-bike-trail:latest
  #   volumes:
  #     - bike-trail-server:/data/bike-trail-server
  #   ports:
  #     - "${BTS_HOST_PORT}:3002"
  #   # networks:
  #   #   - bespoked-bikes
  #   restart: always
  #   # command:
  #   #   - '/bin/sh'
  #   #   - '-c'
  #   #   - '/bin/sleep 30 && nodemon server.js'
  #   depends_on:
  #     - 'postgres'
  #     - 'pgadmin'

# host: host.docker.internal
# database: postgres
# user: postgres
# password: admin

# networks:
#   bespoked-bikes:
    # driver: bridge

volumes:
  # bike-trail-server:
  postgres:
  pgadmin:
