version: '3.5'

services:
  postgres:
    container_name: $PG_CONTAINER_NAME
    image: postgres
    env_file:
      - .docker-env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - $POSTGRES_HOST_PORT:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: $PGADMIN_CONTAINER_NAME
    image: dpage/pgadmin4
    env_file:
      - .docker-env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - $PGADMIN_HOST_PORT:80
    networks:
      - postgres
    restart: unless-stopped

# host: host.docker.internal
# database: postgres
# user: postgres
# password: admin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
